# Generated by Django 5.2 on 2026-06-11 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_lv', models.CharField(blank=True, max_length=200)),
                ('title_ru', models.CharField(blank=True, max_length=200)),
                ('title_en', models.CharField(blank=True, max_length=200)),
                ('title_de', models.CharField(blank=True, max_length=200)),
                ('subtitle_lv', models.TextField(blank=True)),
                ('subtitle_ru', models.TextField(blank=True)),
                ('subtitle_en', models.TextField(blank=True)),
                ('subtitle_de', models.TextField(blank=True)),
                ('button_text_lv', models.CharField(blank=True, max_length=100)),
                ('button_text_ru', models.CharField(blank=True, max_length=100)),
                ('button_text_en', models.CharField(blank=True, max_length=100)),
                ('button_text_de', models.CharField(blank=True, max_length=100)),
                ('button_url', models.CharField(blank=True, max_length=500)),
                ('image', models.ImageField(blank=True, upload_to='banners/')),
                ('image_mobile', models.ImageField(blank=True, upload_to='banners/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Baneris',
                'verbose_name_plural': 'Baneri',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('title_lv', models.CharField(max_length=200)),
                ('title_ru', models.CharField(blank=True, max_length=200)),
                ('title_en', models.CharField(blank=True, max_length=200)),
                ('title_de', models.CharField(blank=True, max_length=200)),
                ('content_lv', models.TextField()),
                ('content_ru', models.TextField(blank=True)),
                ('content_en', models.TextField(blank=True)),
                ('content_de', models.TextField(blank=True)),
                ('meta_description_lv', models.TextField(blank=True)),
                ('meta_description_ru', models.TextField(blank=True)),
                ('meta_description_en', models.TextField(blank=True)),
                ('meta_description_de', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Lapa',
                'verbose_name_plural': 'Lapas',
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address_lv', models.TextField(blank=True)),
                ('address_ru', models.TextField(blank=True)),
                ('address_en', models.TextField(blank=True)),
                ('address_de', models.TextField(blank=True)),
                ('facebook', models.URLField(blank=True)),
                ('instagram', models.URLField(blank=True)),
                ('youtube', models.URLField(blank=True)),
            ],
            options={
                'verbose_name': 'Vietnes iestatījumi',
                'verbose_name_plural': 'Vietnes iestatījumi',
            },
        ),
    ]
