# Generated by Django 5.2 on 2026-06-15 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='font_family',
            field=models.CharField(choices=[('Inter, sans-serif', 'Inter (noklusējums)'), ('Arial, sans-serif', 'Arial'), ('Georgia, serif', 'Georgia'), ("'Oswald', sans-serif", 'Oswald'), ("'Roboto', sans-serif", 'Roboto')], default='Inter, sans-serif', max_length=100),
        ),
        migrations.AddField(
            model_name='banner',
            name='font_size',
            field=models.PositiveIntegerField(default=48, help_text='Virsraksta burtu lielums pikseļos'),
        ),
        migrations.AddField(
            model_name='banner',
            name='image_opacity',
            field=models.FloatField(default=1.0, help_text='0.1 = gandrīz caurspīdīgs, 1.0 = necaurspīdīgs'),
        ),
        migrations.AddField(
            model_name='banner',
            name='text_align',
            field=models.CharField(choices=[('left', 'Pa kreisi'), ('center', 'Centrā'), ('right', 'Pa labi')], default='left', max_length=10),
        ),
        migrations.AddField(
            model_name='banner',
            name='text_valign',
            field=models.CharField(choices=[('top', 'Augšā'), ('middle', 'Vidū'), ('bottom', 'Apakšā')], default='bottom', max_length=10),
        ),
    ]
