# Generated by Django 5.2 on 2026-06-15 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_banner_design_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='button_bg_color',
            field=models.CharField(default='#e30613', help_text='Pogas fona krāsa (hex)', max_length=7),
        ),
        migrations.AddField(
            model_name='banner',
            name='subtitle_color',
            field=models.CharField(default='#cccccc', help_text='Apakšvirsraksta krāsa (hex)', max_length=7),
        ),
        migrations.AddField(
            model_name='banner',
            name='title_color',
            field=models.CharField(default='#ffffff', help_text='Virsraksta krāsa (hex)', max_length=7),
        ),
    ]
