# Generated by Django 5.2 on 2026-06-15 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_banner_color_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='slide_duration',
            field=models.PositiveIntegerField(default=5000, help_text='Rādīšanas ilgums milisekundēs (5000 = 5 sek)'),
        ),
    ]
