# Generated by Django 5.2 on 2026-06-15 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_banner_slide_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='transition_effect',
            field=models.CharField(choices=[('slide', 'Slīdēšana (noklusējums)'), ('fade', 'Izbalēšana'), ('zoom-in', 'Palielināšanās (no maza uz lielu)'), ('zoom-out', 'Samazināšanās (no liela uz mazu)'), ('mosaic', 'Mozaīkas kvadrātiņi')], default='slide', max_length=20),
        ),
    ]
