# Generated by Django 5.2 on 2026-06-15 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_volume_images'),
        ('core', '0005_banner_transition_effect'),
    ]

    operations = [
        migrations.CreateModel(
            name='NavCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_lv', models.CharField(max_length=100)),
                ('name_ru', models.CharField(blank=True, max_length=100)),
                ('name_en', models.CharField(blank=True, max_length=100)),
                ('name_de', models.CharField(blank=True, max_length=100)),
                ('icon', models.CharField(blank=True, default='bi-circle', help_text='Bootstrap Icon klase, piemēram: bi-gear', max_length=100)),
                ('url', models.CharField(blank=True, help_text='Saite (tukšs = ved uz selektoru)', max_length=500)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('vehicle_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nav_categories', to='catalog.vehicletype', verbose_name='Transportlīdzekļa tips')),
            ],
            options={
                'verbose_name': 'Navigācijas apakškategorija',
                'verbose_name_plural': 'Navigācijas apakškategorijas',
                'ordering': ['vehicle_type', 'order', 'name_lv'],
            },
        ),
    ]
