# Generated by Django 5.2 on 2026-06-15 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_volume_images'),
        ('core', '0007_navcategory_cars_data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='navcategory',
            options={'ordering': ['tab_slug', 'order', 'name_lv'], 'verbose_name': 'Navigācijas apakškategorija', 'verbose_name_plural': 'Navigācijas apakškategorijas'},
        ),
        migrations.AddField(
            model_name='navcategory',
            name='tab_slug',
            field=models.SlugField(default='', help_text='Tabs kuram pieder (piemēram: passenger-cars, ieroči)'),
        ),
        migrations.AlterField(
            model_name='navcategory',
            name='url',
            field=models.CharField(blank=True, help_text='Saite uz kuru ved klikšķinot', max_length=500),
        ),
        migrations.AlterField(
            model_name='navcategory',
            name='vehicle_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nav_categories', to='catalog.vehicletype', verbose_name='Transportlīdzekļa tips'),
        ),
    ]
