# Generated by Django 5.2 on 2026-06-15 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_navcategory_populate_tab_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='navcategory',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.navcategory', verbose_name='Vecākkategorija'),
        ),
    ]
