# Generated by Django 5.2 on 2026-06-15 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_navcategory_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navcategory',
            name='tab_slug',
            field=models.SlugField(choices=[('passenger-cars', 'Automašīnas'), ('motorcycle', 'Mototehnika'), ('heavy-truckbus', 'Kravas auto un cita tehnika'), ('ieroci', 'Ieroči')], default='', verbose_name='Tab'),
        ),
    ]
