# Generated by Django 5.2 on 2026-06-15 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_tab_slug_choices'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='navcategory',
            options={'ordering': ['name_lv'], 'verbose_name': 'Navigācijas apakškategorija', 'verbose_name_plural': 'Navigācijas apakškategorijas'},
        ),
    ]
