# Generated by Django 5.2 on 2026-06-15 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_navcategory_ordering'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='whatsapp',
            field=models.CharField(blank=True, help_text='Starptautiskais formāts bez + un atstarpēm, piemēram: 37126123456', max_length=30),
        ),
    ]
