# Generated by Django 5.2 on 2026-06-11 00:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('logo', models.ImageField(blank=True, upload_to='car_brands/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('vehicle_types', models.ManyToManyField(blank=True, to='catalog.vehicletype')),
            ],
            options={
                'verbose_name': 'Auto marka',
                'verbose_name_plural': 'Auto markas',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('year_from', models.PositiveIntegerField(blank=True, null=True)),
                ('year_to', models.PositiveIntegerField(blank=True, help_text='Tukšs = līdz šodienai', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='selector.carbrand')),
                ('vehicle_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.vehicletype')),
            ],
            options={
                'verbose_name': 'Auto modelis',
                'verbose_name_plural': 'Auto modeļi',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CarModification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Piemēram: 2.0 TDI 150hp 2015-2020', max_length=200)),
                ('engine_volume', models.CharField(blank=True, help_text='Piemēram: 2.0', max_length=20)),
                ('fuel_type', models.CharField(blank=True, choices=[('gasoline', 'Benzīns'), ('diesel', 'Dīzelis'), ('hybrid', 'Hibrīds'), ('electric', 'Elektriskais'), ('lpg', 'LPG'), ('other', 'Cits')], max_length=20)),
                ('power_hp', models.PositiveIntegerField(blank=True, null=True, verbose_name='Jauda (HP)')),
                ('year_from', models.PositiveIntegerField(blank=True, null=True)),
                ('year_to', models.PositiveIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('car_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modifications', to='selector.carmodel')),
            ],
            options={
                'verbose_name': 'Auto modifikācija',
                'verbose_name_plural': 'Auto modifikācijas',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProductCompatibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_lv', models.CharField(blank=True, max_length=300)),
                ('note_ru', models.CharField(blank=True, max_length=300)),
                ('note_en', models.CharField(blank=True, max_length=300)),
                ('note_de', models.CharField(blank=True, max_length=300)),
                ('modification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compatible_products', to='selector.carmodification')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compatibilities', to='catalog.product')),
            ],
            options={
                'verbose_name': 'Produkta saderība',
                'verbose_name_plural': 'Produktu saderības',
                'unique_together': {('product', 'modification')},
            },
        ),
    ]
