# Generated by Django 5.2 on 2026-06-16 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selector', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carbrand',
            name='lm_id',
            field=models.CharField(blank=True, db_index=True, help_text='Liqui-Moly OWW ID', max_length=32),
        ),
        migrations.AddField(
            model_name='carmodel',
            name='lm_category',
            field=models.PositiveSmallIntegerField(blank=True, help_text='LM kategorija: 1=Pkw, 2=Van, 3=LKW, 4=Moto', null=True),
        ),
        migrations.AddField(
            model_name='carmodel',
            name='lm_id',
            field=models.CharField(blank=True, db_index=True, help_text='Liqui-Moly OWW ID', max_length=32),
        ),
        migrations.AddField(
            model_name='carmodification',
            name='lm_id',
            field=models.CharField(blank=True, db_index=True, help_text='Liqui-Moly OWW ID', max_length=32),
        ),
        migrations.AddField(
            model_name='carmodification',
            name='oil_viscosity',
            field=models.CharField(blank=True, help_text='Piemēram: 5W-30, 0W-30', max_length=100),
        ),
    ]
