# Generated by Django 5.2 on 2026-06-17 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selector', '0002_lm_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='carmodification',
            name='oil_spec',
            field=models.CharField(blank=True, help_text='OEM apstiprinājumi, piemēram: BMW LL-04, ACEA C3, VW 504.00', max_length=300),
        ),
    ]
