# Generated by Django 5.2 on 2026-06-11 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='company',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='company_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Uzņēmuma nosaukums'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='customer_type',
            field=models.CharField(choices=[('private', 'Privāts pircējs'), ('company', 'Uzņēmums / Juridiska persona')], default='private', max_length=10, verbose_name='Klienta tips'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='delivery_address',
            field=models.CharField(blank=True, max_length=300, verbose_name='Faktiskā adrese'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='delivery_city',
            field=models.CharField(blank=True, max_length=100, verbose_name='Pilsēta (faktiskā)'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='delivery_country',
            field=models.CharField(blank=True, choices=[('LV', 'Latvija'), ('LT', 'Lietuva'), ('EE', 'Igaunija'), ('FI', 'Somija'), ('SE', 'Zviedrija'), ('DE', 'Vācija'), ('PL', 'Polija'), ('OTHER', 'Cita')], default='LV', max_length=10, verbose_name='Valsts (faktiskā)'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='delivery_postal_code',
            field=models.CharField(blank=True, max_length=20, verbose_name='Pasta indekss (faktiskā)'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='delivery_same',
            field=models.BooleanField(default=True, verbose_name='Faktiskā adrese = juridiskajai'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='legal_address',
            field=models.CharField(blank=True, max_length=300, verbose_name='Juridiskā adrese'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='legal_city',
            field=models.CharField(blank=True, max_length=100, verbose_name='Pilsēta'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='legal_country',
            field=models.CharField(choices=[('LV', 'Latvija'), ('LT', 'Lietuva'), ('EE', 'Igaunija'), ('FI', 'Somija'), ('SE', 'Zviedrija'), ('DE', 'Vācija'), ('PL', 'Polija'), ('OTHER', 'Cita')], default='LV', max_length=10, verbose_name='Valsts'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='legal_postal_code',
            field=models.CharField(blank=True, max_length=20, verbose_name='Pasta indekss'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='newsletter',
            field=models.BooleanField(default=True, verbose_name='Saņemt jaunumus'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=30, verbose_name='Tālrunis'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='reg_nr',
            field=models.CharField(blank=True, max_length=50, verbose_name='Reģistrācijas Nr.'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='vat_nr',
            field=models.CharField(blank=True, max_length=50, verbose_name='PVN reģ. Nr.'),
        ),
        migrations.DeleteModel(
            name='Address',
        ),
    ]
