# Generated by Django 5.2 on 2026-06-11 00:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('logo', models.ImageField(blank=True, upload_to='brands/')),
                ('description_lv', models.TextField(blank=True)),
                ('description_ru', models.TextField(blank=True)),
                ('description_en', models.TextField(blank=True)),
                ('description_de', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Zīmols',
                'verbose_name_plural': 'Zīmoli',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='VehicleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_lv', models.CharField(max_length=100)),
                ('name_ru', models.CharField(blank=True, max_length=100)),
                ('name_en', models.CharField(blank=True, max_length=100)),
                ('name_de', models.CharField(blank=True, max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('icon', models.CharField(blank=True, max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Transportlīdzekļa tips',
                'verbose_name_plural': 'Transportlīdzekļu tipi',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_lv', models.CharField(max_length=200)),
                ('name_ru', models.CharField(blank=True, max_length=200)),
                ('name_en', models.CharField(blank=True, max_length=200)),
                ('name_de', models.CharField(blank=True, max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(blank=True, upload_to='categories/')),
                ('icon', models.CharField(blank=True, help_text='Bootstrap icon class, piemēram: bi-droplet', max_length=100)),
                ('description_lv', models.TextField(blank=True)),
                ('description_ru', models.TextField(blank=True)),
                ('description_en', models.TextField(blank=True)),
                ('description_de', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='catalog.category')),
            ],
            options={
                'verbose_name': 'Kategorija',
                'verbose_name_plural': 'Kategorijas',
                'ordering': ['order', 'name_lv'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_lv', models.CharField(max_length=300)),
                ('name_ru', models.CharField(blank=True, max_length=300)),
                ('name_en', models.CharField(blank=True, max_length=300)),
                ('name_de', models.CharField(blank=True, max_length=300)),
                ('slug', models.SlugField(unique=True)),
                ('sku', models.CharField(blank=True, max_length=100, verbose_name='Artikuls')),
                ('product_type', models.CharField(choices=[('oil', 'Eļļa'), ('additive', 'Piedeva'), ('fluid', 'Šķidrums'), ('cosmetics', 'Kosmētika'), ('other', 'Cits')], default='oil', max_length=20)),
                ('description_lv', models.TextField(blank=True)),
                ('description_ru', models.TextField(blank=True)),
                ('description_en', models.TextField(blank=True)),
                ('description_de', models.TextField(blank=True)),
                ('short_description_lv', models.TextField(blank=True)),
                ('short_description_ru', models.TextField(blank=True)),
                ('short_description_en', models.TextField(blank=True)),
                ('short_description_de', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='products/')),
                ('image2', models.ImageField(blank=True, upload_to='products/')),
                ('image3', models.ImageField(blank=True, upload_to='products/')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price_old', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('volume_ml', models.PositiveIntegerField(blank=True, null=True, verbose_name='Tilpums (ml)')),
                ('viscosity', models.CharField(blank=True, choices=[('0W-20', '0W-20'), ('0W-30', '0W-30'), ('0W-40', '0W-40'), ('5W-30', '5W-30'), ('5W-40', '5W-40'), ('10W-40', '10W-40'), ('10W-60', '10W-60'), ('15W-40', '15W-40'), ('20W-50', '20W-50'), ('', 'Nav piemērojams')], max_length=20)),
                ('specifications_lv', models.TextField(blank=True, help_text='API, ACEA u.c. specifikācijas')),
                ('specifications_ru', models.TextField(blank=True)),
                ('specifications_en', models.TextField(blank=True)),
                ('specifications_de', models.TextField(blank=True)),
                ('is_featured', models.BooleanField(default=False, verbose_name='Izceltais produkts')),
                ('is_new', models.BooleanField(default=False, verbose_name='Jaunums')),
                ('is_sale', models.BooleanField(default=False, verbose_name='Izpārdošana')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='catalog.brand')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='catalog.category')),
                ('vehicle_types', models.ManyToManyField(blank=True, related_name='products', to='catalog.vehicletype')),
            ],
            options={
                'verbose_name': 'Produkts',
                'verbose_name_plural': 'Produkti',
                'ordering': ['order', 'name_lv'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.product')),
            ],
            options={
                'verbose_name': 'Produkta attēls',
                'verbose_name_plural': 'Produkta attēli',
                'ordering': ['order'],
            },
        ),
    ]
