# Generated by Django 5.2 on 2026-06-11 01:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_lv', models.CharField(max_length=150)),
                ('name_ru', models.CharField(blank=True, max_length=150)),
                ('name_en', models.CharField(blank=True, max_length=150)),
                ('name_de', models.CharField(blank=True, max_length=150)),
                ('slug', models.SlugField(unique=True)),
                ('icon', models.CharField(blank=True, max_length=100)),
                ('description_lv', models.TextField(blank=True)),
                ('description_ru', models.TextField(blank=True)),
                ('description_en', models.TextField(blank=True)),
                ('description_de', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Pielietojums',
                'verbose_name_plural': 'Pielietojumi',
                'ordering': ['order', 'name_lv'],
            },
        ),
        migrations.AddField(
            model_name='productimage',
            name='alt_text',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='applications',
            field=models.ManyToManyField(blank=True, related_name='products', to='catalog.productapplication'),
        ),
        migrations.CreateModel(
            name='ProductSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_lv', models.CharField(max_length=150)),
                ('name_ru', models.CharField(blank=True, max_length=150)),
                ('name_en', models.CharField(blank=True, max_length=150)),
                ('name_de', models.CharField(blank=True, max_length=150)),
                ('value', models.CharField(max_length=500)),
                ('order', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specifications', to='catalog.product')),
            ],
            options={
                'verbose_name': 'Specifikācija',
                'verbose_name_plural': 'Specifikācijas',
                'ordering': ['order', 'name_lv'],
            },
        ),
        migrations.CreateModel(
            name='ProductVolume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='Piemēram: 1L, 4L, 5L, 250ml', max_length=50)),
                ('volume_ml', models.PositiveIntegerField(blank=True, null=True)),
                ('sku', models.CharField(blank=True, max_length=100, verbose_name='Artikuls')),
                ('price', models.DecimalField(decimal_places=2, help_text='Cena AR PVN', max_digits=10)),
                ('price_old', models.DecimalField(blank=True, decimal_places=2, help_text='Vecā cena AR PVN', max_digits=10, null=True)),
                ('stock', models.PositiveIntegerField(blank=True, help_text='Tukšs = neierobežots', null=True)),
                ('is_default', models.BooleanField(default=False, verbose_name='Noklusētais tilpums')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volumes', to='catalog.product')),
            ],
            options={
                'verbose_name': 'Tilpums / Cena',
                'verbose_name_plural': 'Tilpumi / Cenas',
                'ordering': ['order', 'volume_ml', 'price'],
            },
        ),
    ]
