# Generated by Django 5.2 on 2026-06-11 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_productapplication_productimage_alt_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='barcode',
            field=models.CharField(blank=True, max_length=50, verbose_name='Svītru kods (EAN/UPC)'),
        ),
    ]
