# Generated by Django 5.2 on 2026-06-11 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_product_barcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvolume',
            name='label',
            field=models.CharField(choices=[('0.5L', '0.5 L'), ('1L', '1 L'), ('2L', '2 L'), ('4L', '4 L'), ('5L', '5 L'), ('20L', '20 L'), ('60L', '60 L'), ('200L', '200 L')], max_length=10, verbose_name='Tilpums'),
        ),
        migrations.AlterField(
            model_name='productvolume',
            name='volume_ml',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
    ]
