# Generated by Django 5.2 on 2026-06-11 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_volume_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvolume',
            name='label',
            field=models.CharField(choices=[('9ml', '9 ml'), ('25ml', '25 ml'), ('250ml', '250 ml'), ('400ml', '400 ml'), ('500ml', '500 ml'), ('0.5L', '0.5 L'), ('1L', '1 L'), ('2L', '2 L'), ('4L', '4 L'), ('5L', '5 L'), ('20L', '20 L'), ('60L', '60 L'), ('200L', '200 L')], max_length=10, verbose_name='Tilpums'),
        ),
    ]
