# Generated by Django 5.2 on 2026-06-12 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_reviews_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='requirements_de',
            field=models.TextField(blank=True, verbose_name='Prasības DE'),
        ),
        migrations.AddField(
            model_name='product',
            name='requirements_en',
            field=models.TextField(blank=True, verbose_name='Prasības EN'),
        ),
        migrations.AddField(
            model_name='product',
            name='requirements_lv',
            field=models.TextField(blank=True, help_text='Transportlīdzekļu prasības, standarti', verbose_name='Prasības LV'),
        ),
        migrations.AddField(
            model_name='product',
            name='requirements_ru',
            field=models.TextField(blank=True, verbose_name='Prasības RU'),
        ),
        migrations.AddField(
            model_name='product',
            name='technical_info_de',
            field=models.TextField(blank=True, verbose_name='Tehniskā informācija DE'),
        ),
        migrations.AddField(
            model_name='product',
            name='technical_info_en',
            field=models.TextField(blank=True, verbose_name='Tehniskā informācija EN'),
        ),
        migrations.AddField(
            model_name='product',
            name='technical_info_lv',
            field=models.TextField(blank=True, verbose_name='Tehniskā informācija LV'),
        ),
        migrations.AddField(
            model_name='product',
            name='technical_info_ru',
            field=models.TextField(blank=True, verbose_name='Tehniskā informācija RU'),
        ),
        migrations.AlterField(
            model_name='product',
            name='specifications_de',
            field=models.TextField(blank=True, verbose_name='Specifikācijas DE'),
        ),
        migrations.AlterField(
            model_name='product',
            name='specifications_en',
            field=models.TextField(blank=True, verbose_name='Specifikācijas EN'),
        ),
        migrations.AlterField(
            model_name='product',
            name='specifications_lv',
            field=models.TextField(blank=True, help_text='API, ACEA u.c. specifikācijas', verbose_name='Specifikācijas LV'),
        ),
        migrations.AlterField(
            model_name='product',
            name='specifications_ru',
            field=models.TextField(blank=True, verbose_name='Specifikācijas RU'),
        ),
    ]
