# Generated by Django 5.2 on 2026-06-12 05:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_product_tech_requirements'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackagingTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Piemēram: 1L kanna, 4L kanna, EX120 blister 6gab', max_length=100, verbose_name='Nosaukums')),
                ('auto_apply_to_volume', models.CharField(blank=True, help_text='Ja aizpildīts — jauni šī tilpuma ieraksti paņems šos izmērus', max_length=10, verbose_name='Automātiski piemērot tilpumam')),
                ('weight_g', models.PositiveIntegerField(help_text='Kopā ar iepakojumu', verbose_name='Svars (g)')),
                ('length_mm', models.PositiveIntegerField(verbose_name='Garums (mm)')),
                ('width_mm', models.PositiveIntegerField(verbose_name='Platums (mm)')),
                ('height_mm', models.PositiveIntegerField(verbose_name='Augstums (mm)')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='Piezīme')),
            ],
            options={
                'verbose_name': 'Iepakojuma šablons',
                'verbose_name_plural': 'Iepakojuma šabloni',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='productvolume',
            name='height_mm',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Augstums (mm)'),
        ),
        migrations.AddField(
            model_name='productvolume',
            name='length_mm',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Garums (mm)'),
        ),
        migrations.AddField(
            model_name='productvolume',
            name='weight_g',
            field=models.PositiveIntegerField(blank=True, help_text='Atstāj tukšu — paņems no šablona', null=True, verbose_name='Svars (g)'),
        ),
        migrations.AddField(
            model_name='productvolume',
            name='width_mm',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Platums (mm)'),
        ),
        migrations.AddField(
            model_name='productvolume',
            name='packaging',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='volumes', to='catalog.packagingtemplate', verbose_name='Iepakojuma šablons'),
        ),
    ]
