# Generated by Django 5.2 on 2026-06-12 05:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_packaging_template'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_lv', models.CharField(max_length=150, verbose_name='Prasība')),
                ('name_ru', models.CharField(blank=True, max_length=150)),
                ('name_en', models.CharField(blank=True, max_length=150)),
                ('name_de', models.CharField(blank=True, max_length=150)),
                ('value', models.CharField(max_length=500, verbose_name='Vērtība')),
                ('order', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirement_items', to='catalog.product')),
            ],
            options={
                'verbose_name': 'Prasība',
                'verbose_name_plural': 'Prasības',
                'ordering': ['order', 'name_lv'],
            },
        ),
        migrations.CreateModel(
            name='ProductTechnicalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_lv', models.CharField(max_length=150, verbose_name='Parametrs')),
                ('name_ru', models.CharField(blank=True, max_length=150)),
                ('name_en', models.CharField(blank=True, max_length=150)),
                ('name_de', models.CharField(blank=True, max_length=150)),
                ('value', models.CharField(max_length=500, verbose_name='Vērtība')),
                ('order', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technical_items', to='catalog.product')),
            ],
            options={
                'verbose_name': 'Tehniskā informācija',
                'verbose_name_plural': 'Tehniskā informācija',
                'ordering': ['order', 'name_lv'],
            },
        ),
    ]
