# Generated by Django 5.2 on 2026-06-12 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_tech_requirements_tables'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvolume',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/volumes/', verbose_name='Foto'),
        ),
    ]
