# Generated by Django 5.2 on 2026-06-13 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_video_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductVolumeImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/volumes/')),
                ('alt_text', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('volume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_images', to='catalog.productvolume')),
            ],
            options={
                'verbose_name': 'Tilpuma attēls',
                'verbose_name_plural': 'Tilpuma attēli',
                'ordering': ['order'],
            },
        ),
    ]
