# Generated by Django 5.2 on 2026-06-15 21:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_product_nav_categories'),
        ('core', '0022_navcategory_ordering'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='nav_categories',
        ),
        migrations.AddField(
            model_name='product',
            name='nav_subcategory',
            field=models.ForeignKey(blank=True, limit_choices_to={'parent__isnull': False}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='core.navcategory', verbose_name='Apakškategorija (navigācija)'),
        ),
    ]
