# Generated by Django 5.2 on 2026-06-15 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_nav_subcategory_fk'),
        ('core', '0024_sitesettings_viber'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='nav_tabs',
            field=models.ManyToManyField(blank=True, limit_choices_to={'parent__isnull': True}, related_name='tab_products', to='core.navcategory', verbose_name='Kategorijas'),
        ),
    ]
