# Generated by Django 5.2 on 2026-06-15 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_product_nav_tabs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='nav_tabs',
        ),
        migrations.AddField(
            model_name='product',
            name='tab_heavy_truckbus',
            field=models.BooleanField(default=False, verbose_name='Kravas automašīnas un cita tehnika'),
        ),
        migrations.AddField(
            model_name='product',
            name='tab_ieroci',
            field=models.BooleanField(default=False, verbose_name='Ieroči'),
        ),
        migrations.AddField(
            model_name='product',
            name='tab_motorcycle',
            field=models.BooleanField(default=False, verbose_name='Mototehnika'),
        ),
        migrations.AddField(
            model_name='product',
            name='tab_passenger_cars',
            field=models.BooleanField(default=False, verbose_name='Automašīnas'),
        ),
    ]
