# Generated by Django 5.2 on 2026-06-17 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_product_tab_booleans'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_type',
        ),
        migrations.AlterField(
            model_name='product',
            name='viscosity',
            field=models.CharField(blank=True, choices=[('0W-16', '0W-16'), ('0W-20', '0W-20'), ('0W-30', '0W-30'), ('0W-40', '0W-40'), ('5W-20', '5W-20'), ('5W-30', '5W-30'), ('5W-40', '5W-40'), ('5W-50', '5W-50'), ('10W-30', '10W-30'), ('10W-40', '10W-40'), ('10W-60', '10W-60'), ('15W-40', '15W-40'), ('20W-50', '20W-50'), ('', 'Nav piemērojams')], max_length=20),
        ),
        migrations.AlterField(
            model_name='productvolume',
            name='label',
            field=models.CharField(choices=[('8ml', '8 ml'), ('9ml', '9 ml'), ('25ml', '25 ml'), ('250ml', '250 ml'), ('320ml', '320 ml'), ('400ml', '400 ml'), ('500ml', '500 ml'), ('0.5L', '0.5 L'), ('1L', '1 L'), ('2L', '2 L'), ('4L', '4 L'), ('5L', '5 L'), ('20L', '20 L'), ('60L', '60 L'), ('200L', '200 L')], max_length=10, verbose_name='Tilpums'),
        ),
    ]
