# Generated by Django 5.2 on 2026-06-17 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0017_remove_product_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvolume',
            name='barcode',
            field=models.CharField(blank=True, max_length=50, verbose_name='Svītru kods'),
        ),
    ]
