# Generated by Django 5.2 on 2026-06-11 01:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0002_productapplication_productimage_alt_text_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(editable=False, max_length=20, unique=True)),
                ('session_key', models.CharField(blank=True, max_length=40)),
                ('status', models.CharField(choices=[('pending', 'Gaida apstiprinājumu'), ('confirmed', 'Apstiprināts'), ('processing', 'Tiek apstrādāts'), ('shipped', 'Nosūtīts'), ('delivered', 'Piegādāts'), ('cancelled', 'Atcelts')], default='pending', max_length=20)),
                ('payment_method', models.CharField(choices=[('bank', 'Bankas pārskaitījums'), ('card', 'Kredītkarte')], default='bank', max_length=20)),
                ('payment_status', models.CharField(choices=[('pending', 'Gaida'), ('paid', 'Samaksāts'), ('failed', 'Neizdevās'), ('refunded', 'Atmaksāts')], default='pending', max_length=20)),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=30)),
                ('address_line1', models.CharField(max_length=300)),
                ('address_line2', models.CharField(blank=True, max_length=300)),
                ('city', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=20)),
                ('country', models.CharField(default='Latvija', max_length=100)),
                ('company', models.CharField(blank=True, max_length=200)),
                ('vat_nr', models.CharField(blank=True, max_length=50)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('vat_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('shipping_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('notes', models.TextField(blank=True)),
                ('admin_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pasūtījums',
                'verbose_name_plural': 'Pasūtījumi',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=300)),
                ('volume_label', models.CharField(blank=True, max_length=50)),
                ('sku', models.CharField(blank=True, max_length=100)),
                ('price_with_vat', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.product')),
                ('volume', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.productvolume')),
            ],
            options={
                'verbose_name': 'Pasūtījuma pozīcija',
                'verbose_name_plural': 'Pasūtījuma pozīcijas',
            },
        ),
    ]
