# Generated by Django 5.2 on 2026-06-11 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='invoice_date',
            field=models.DateField(blank=True, null=True, verbose_name='Rēķina datums'),
        ),
        migrations.AddField(
            model_name='order',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=30, verbose_name='Rēķina numurs'),
        ),
        migrations.AddField(
            model_name='order',
            name='invoice_sent',
            field=models.BooleanField(default=False, verbose_name='Rēķins nosūtīts'),
        ),
        migrations.AddField(
            model_name='order',
            name='invoice_sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Nosūtīts'),
        ),
    ]
